USE [master]
GO

/****** Object:  Database [LizPhonebook]    Script Date: 2021/05/20 17:03:37 ******/
CREATE DATABASE [LizPhonebook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LizPhonebook', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.LIZ\MSSQL\DATA\LizPhonebook.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LizPhonebook_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.LIZ\MSSQL\DATA\LizPhonebook_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LizPhonebook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LizPhonebook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LizPhonebook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LizPhonebook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LizPhonebook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LizPhonebook] SET ARITHABORT OFF 
GO

ALTER DATABASE [LizPhonebook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LizPhonebook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LizPhonebook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LizPhonebook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LizPhonebook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LizPhonebook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LizPhonebook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LizPhonebook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LizPhonebook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LizPhonebook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LizPhonebook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LizPhonebook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LizPhonebook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LizPhonebook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LizPhonebook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LizPhonebook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LizPhonebook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LizPhonebook] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LizPhonebook] SET  MULTI_USER 
GO

ALTER DATABASE [LizPhonebook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LizPhonebook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LizPhonebook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LizPhonebook] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LizPhonebook] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LizPhonebook] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LizPhonebook] SET  READ_WRITE 
GO


